### ISSUE TITLE
[v2 false positive ?] Assets not being served but why ?

### ISSUE THREAD

**Issue by tristanbes** [mariusv/nginx-badbot-blocker#127]
Hello,

On this website, using v2 of nginx-badbot-blocker : 
http://julien-moyret-parqueteur.specialisteparquet.com/ 
which is one of our 4000 website hosted on the same application (using same vhost), all assets doesn't load anymore (and all websites assets hosted under `*.specialisteparquet.com`)

If accessing directly, nginx (through varnish) serve them with no problem: 
http://julien-moyret-parqueteur.specialisteparquet.com/css/reset.css?v=15

This behaviour leads me to think that something triggers the "bad referrer" rule on your badbot-blocker. If I comment out `include /etc/nginx/bots.d/blokbots.conf`, all assets are being served again.

I search on the bad referrer list and I can't find (and there's no reason to find it) our domain inside it. So why on this domain/subdomains, it's being flagged as bad bot/redirect ? 

Thank you :-)

PS: I didn't enabled the anti-ddos rules

**Comment by tristanbes** [comment]
Adding `"~*specialisteparquet.com" 	0;` to `whitelist-domains.conf` does not fix the issue.

**Comment by mitchellkrogza** [comment]
Been away, back in office tomorrow will have a look. Missed the thread on
this and your problem but will look in the morning

**Comment by mitchellkrogza** [comment]
Ok just read the whole thread, I'll sort this for you tomorrow might be something triggering a false positive. Will update you once I have had a look.

**Comment by tristanbes** [comment]
ok :-)

**Comment by mitchellkrogza** [comment]
Appears to be a false positive issue. I did curl tests against my sites using your domain name as the referrer and this was the results from both the Nginx and Apache Bad Bot Blocker's below.

```
curl -I https://mysite.com -e http://julien-moyret-parqueteur.specialisteparquet.com/
curl: (52) Empty reply from server
```

and

```
curl -I https://mysite.com -e http://julien-moyret-parqueteur.specialisteparquet.com/

HTTP/1.1 403 Forbidden
Date: Tue, 04 Jul 2017 08:54:24 GMT
Server: Apache
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
Content-Type: text/html; charset=iso-8859-1
```
I will find out what is being picked up from the blocklist that may be causing this.

**Comment by tristanbes** [comment]
Thank you for your investigation. Being treated as bad referrer/bad bot isn't rewarding :D

**Comment by mitchellkrogza** [comment]
😊  sorry ... it happens very seldom, am investigating the issue now to see what is throwing a flag from your domain name. I will definitely find it, could be a syntax change on the regex required on the bad referrers section. Will update you through the day.

**Comment by mitchellkrogza** [comment]
Found the problem. Will push out a fix shortly.

For now, edit your /etc/nginx/bots.d/bad-referrer-words.conf file and delete this line

`	"~*cialis"		1;`

It's picking up **cialis** within your domain string. 

http://julien-moyret-parqueeur.spe**cialis**eparque.com

You can actually empty the entire bad-referrer-words.conf file as it CAN lead to false positives as you have seen. New update coming shortly will have an empty bad-referrer-words.conf file only with examples for people and will document and explain this exact problem you ran into with big warnings of how that include file if used incorrectly can cause serious issues.

Thanks for reporting this.

**Comment by tristanbes** [comment]
thanks for your feedback. Will wait for your push before re-enabling the inclusion of `blokbots.conf`

**Comment by mitchellkrogza** [comment]
Busy on it, some changes in a recent bash update on Ubuntu causing headaches to generating the new list. Busy fixing all of that right now.

**Comment by mitchellkrogza** [comment]
@tristanbes please pull latest blacklist.conf file fixed in https://github.com/mariusv/nginx-badbot-blocker/commit/c8f377e0bc3bf19c9b12c1fb10c72f29ec5d6437

`sudo wget https://github.com/mariusv/nginx-badbot-blocker/raw/master/VERSION_2/conf.d/blacklist.conf -O /etc/nginx/conf.d/blacklist.conf`

then re-enable your include of `include /etc/nginx/bots.d/blockbots.conf;` in your vhost

and then reload nginx and test, you will see your problem should be gone now.

**Comment by tristanbes** [comment]
![1__root_lux___etc_nginx_bots_d__ssh_](https://user-images.githubusercontent.com/346010/27830186-8d70e1ca-60c5-11e7-9b36-f81b406b3054.png)

I just fetched the updated script version + nginx reloaded, error still happening.

And, I see a false positive too in this request: 
```
4 Jul 2017 14:10:57.346  "time": "2017-07-04T14:10:51+02:00", "http_x_forwarded_for": "34.227.93.122, 10.108.21.222", "remote_addr": "127.0.0.1", "remote_user": "-", "body_bytes_sent": "0", "request_time": "0.000", "status": "444", "request": "GET /queue/keyword/process?queue_size=15964&keyword_id=992&callback=https%3A%2F%2Fadmin.yproximite.fr%2F11836%2Fkeyword%2F992%2Frefresh%2Fcallback&url=sme.installateur-alarme-proxeo.fr HTTP/1.1", "request_method": "GET", "http_referrer": "-", "http_user_agent": "GuzzleHttp/6.1.1 curl/7.35.0 PHP/5.6.5-1+deb.sury.org~trusty+1" lux/access.log Context
```

It's a worker service that is calling our domain to push some information. Maybe I should allow `remove-user`:`-` ? What do you suggest ?

**Comment by tristanbes** [comment]
PS: Is there a way just to check for badbots/referer and disable extra features (user agents...) to have something more "predictable" ?

**Comment by mitchellkrogza** [comment]
@tristanbes thanks for reporting back. Need to dig a little deeper into this and formulate a solution. A recent update to bash/dash on Ubuntu is causing me major headaches right now. Started last week. Any input string in my generator script that contains a lowercase "n" is being stripped out. Trying to get to the bottom of it and will then push out a new version which will allow to enable or disable features of the blocker. Apologies, for now, leave it disabled on your site and I will get back to you as soon as I have a solution.

**Comment by mitchellkrogza** [comment]
@tristanbes try the latest blacklist.conf just pushed out. Fixed the bash issue I was having and also removed GuzzleHTTP from the bad bots list for now. Please try again and let me know. 

I will still work out a way to give users the option to turn on/off the checking of bad bots and only check for referrers. But try with the latest version and let me know.

**Comment by tristanbes** [comment]
Sadly still not working for the original website http://julien-moyret-parqueteur.specialisteparquet.com/

**Comment by mitchellkrogza** [comment]
@tristanbes I did test it using your referrer and it passed, can you post another log example. I need to implement some regex changes in the bad-referrers section which are also causing false positives which should be sorted tomorrow.

**Comment by tristanbes** [comment]
is this enough for you ? https://gist.github.com/tristanbes/4d4b11b680e3927ba4ce4f2c9c76e368

**Comment by mitchellkrogza** [comment]
Just ran a curl test as follows, so it's not failing on the referrer string. 

```curl -I http://julien-moyret-parqueteur.specialisteparquet.com/ -e http://julien-moyret-parqueteur.specialisteparquet.com/
HTTP/1.1 200 OK
Age: 0
Via: 1.1 varnish (Varnish/5.0)
Content-Type: text/html; charset=UTF-8
Cache-Control: no-cache, private
Server: nginx
Vary: Accept-Encoding
Set-Cookie: PHPSESSID=91f73i7ejkode16vlg729jnusd; expires=Fri, 21-Jul-2017 15:11:28 GMT; Max-Age=864000; path=/; HttpOnly
Date: Tue, 11 Jul 2017 15:11:28 GMT
X-Backend: lux
X-Varnish: 15794646
Connection: Close
```

and another using the user-agent string in your logs and it get's through on that too ??

```
curl -A "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36" http://julien-moyret-parqueteur.specialisteparquet.com/

<!DOCTYPE html>
<html>
```

Very strange indeed.

**Comment by mitchellkrogza** [comment]
Please can you post some lines from your error.log

**Comment by mitchellkrogza** [comment]
When i run curl tests calling the resources in your logs, I get the following:

```
$ curl -I http://julien-moyret-parqueteur.specialisteparquet.com/media/original/slider-4-51563.jpg -e http://julien-moyret-parqueteur.specialisteparquet.com/
HTTP/1.1 503 Backend fetch failed
Age: 0
Via: 1.1 varnish (Varnish/5.0)
Content-Type: text/html; charset=utf-8
Date: Tue, 11 Jul 2017 15:25:10 GMT
Server: Varnish
Retry-After: 5
X-Varnish: 16190003
Connection: Close

$ curl -I http://julien-moyret-parqueteur.specialisteparquet.com/media/original/slider2-53737.jpg -e http://julien-moyret-parqueteur.specialisteparquet.com/
HTTP/1.1 503 Backend fetch failed
Age: 0
Via: 1.1 varnish (Varnish/5.0)
Content-Type: text/html; charset=utf-8
Date: Tue, 11 Jul 2017 15:25:46 GMT
Server: Varnish
Retry-After: 5
X-Varnish: 19732581
Connection: Close

$ curl -I http://julien-moyret-parqueteur.specialisteparquet.com/js/nl2br.js -e http://julien-moyret-parqueteur.specialisteparquet.com/
HTTP/1.1 503 Backend fetch failed
Age: 0
Via: 1.1 varnish (Varnish/5.0)
Content-Type: text/html; charset=utf-8
Date: Tue, 11 Jul 2017 15:26:08 GMT
Server: Varnish
Retry-After: 5
X-Varnish: 16125267
Connection: Close

$ curl -I http://julien-moyret-parqueteur.specialisteparquet.com/js/article_slider.min.js -e http://julien-moyret-parqueteur.specialisteparquet.com/
HTTP/1.1 503 Backend fetch failed
Age: 0
Via: 1.1 varnish (Varnish/5.0)
Content-Type: text/html; charset=utf-8
Date: Tue, 11 Jul 2017 15:26:59 GMT
Server: Varnish
Retry-After: 5
X-Varnish: 16157490
Connection: Close

```

**Comment by tristanbes** [comment]
user -> varnish -> nginx
user -> varnish <-> nginx returns 444
user <-> varnish return 503 because <-> nginx returned 444

error.log are empty which is normal since there are no errors occuring (444 status code ain't no error)

**Comment by mitchellkrogza** [comment]
This truly is so weird 😖  but I will get to the bottom of this for you. It's weird my curl tests all allow me through. Just as a test is there anyway for you to bypass varnish to do a test for now? Need to rule out that something is not going weird in cacheing. Are you sure you have the latest blacklist `sudo wget https://raw.githubusercontent.com/mariusv/nginx-badbot-blocker/master/VERSION_2/conf.d/blacklist.conf -O /etc/nginx/conf.d/blacklist.conf`

**Comment by tristanbes** [comment]
Last updated: tue jul 4 15:50:06
I have a task updating your banlist each day ;-)

Actually I can't bypass varnish, but varnish is off. All it does for us is add a X-backend information to know which backend server answered you. He never caches anything.

**Comment by mitchellkrogza** [comment]
@tristanbes please can you try out this test unit I just pushed out for you. `sudo wget https://raw.githubusercontent.com/mariusv/nginx-badbot-blocker/master/VERSION_2/Test_Unit/blacklist.conf -O /etc/nginx/conf.d/blacklist.conf` reload nginx and let me know if anything changes.

**Comment by mitchellkrogza** [comment]
If that doesn't work please post your vhost config file here so I can see if anything else might be at play here.

**Comment by tristanbes** [comment]
Sorry to inform you it's not working :D 

Vhost is : https://gist.github.com/tristanbes/064756bdd24f226da3cf5a39ffe4d679

**Comment by mitchellkrogza** [comment]
Please try the change suggested at https://gist.github.com/tristanbes/064756bdd24f226da3cf5a39ffe4d679 moving the include lower down in the chain.

**Comment by tristanbes** [comment]
No change on my side.

**Comment by tristanbes** [comment]
no, thanks for your time ;-)

**Comment by mitchellkrogza** [comment]
What is very weird is that my earlier curl tests allowed me through now they don't.

```
curl -I http://julien-moyret-parqueteur.specialisteparquet.com/ -e http://julien-moyret-parqueteur.specialisteparquet.com/
HTTP/1.1 503 Backend fetch failed
Age: 0
Via: 1.1 varnish (Varnish/5.0)
Content-Type: text/html; charset=utf-8
Date: Tue, 11 Jul 2017 16:06:59 GMT
Server: Varnish
Retry-After: 5
X-Varnish: 14329494
Connection: Close
```
but a little earlier when i ran the same curl I got 200 OK

```
curl -I http://julien-moyret-parqueteur.specialisteparquet.com/ -e http://julien-moyret-parqueteur.specialisteparquet.com/

HTTP/1.1 200 OK
Age: 0
Via: 1.1 varnish (Varnish/5.0)
Content-Type: text/html; charset=UTF-8
Cache-Control: no-cache, private
Server: nginx
Vary: Accept-Encoding
Set-Cookie: PHPSESSID=91f73i7ejkode16vlg729jnusd; expires=Fri, 21-Jul-2017 15:11:28 GMT; Max-Age=864000; path=/; HttpOnly
Date: Tue, 11 Jul 2017 15:11:28 GMT
X-Backend: lux
X-Varnish: 15794646
Connection: Close
```

**Comment by tristanbes** [comment]
It maybe me that enabled/disabled your ban list depending on your demands in order to avoid client phone call for his broken website. 

Depending on your timezone, I could leave during 1 hour tomorrow for example the banlist if that helps you ?

**Comment by mitchellkrogza** [comment]
My time zone is gmt +2 but for now leave it disabled and I will try and
trace what's causing the false positives. Will let you know tomorrow a time
to enable it with a new test unit hopefully and then I can test. It's a
riddle but I like riddles as annoying as they may be, but all in all it
must be solved as it could be happening to other users without their
knowledge.

**Comment by mitchellkrogza** [comment]
@tristanbes please try the latest blacklist - https://github.com/mariusv/nginx-badbot-blocker/blob/master/VERSION_2/conf.d/blacklist.conf 

Have made a lot of changes to regex patterns on User-Agents and Referrers to prevent false positives. Please test and come back to me with results. 👍

**Comment by mitchellkrogza** [comment]
@tristanbes any luck yet?

**Comment by tristanbes** [comment]
Hello, sorry for delay, wasn't working. 
Just tested with master version of blacklist.conf and the problem is still happening.

**Comment by mitchellkrogza** [comment]
@tristanbes this is truly strange. Please can you send me some more detailed logs of when it's blocking all assets loading on your site. Even any varnish logs or anything else to help me see what is going on and where.

**Comment by mitchellkrogza** [comment]
@tristanbes I am most interested to see the logs where this excerpt originally came from 

```
4 Jul 2017 14:10:57.346  "time": "2017-07-04T14:10:51+02:00", 
"http_x_forwarded_for": "34.227.93.122, 10.108.21.222", "remote_addr": "127.0.0.1", "remote_user": "-", "body_bytes_sent": "0",
 "request_time": "0.000", "status": "444", "request": "GET /queue/keyword/process?queue_size=15964&keyword_id=992&callback=https%3A%2F%2Fadmin.yproximite.fr%2F11836%2Fkeyword%2F992%2Frefresh%2Fcallback&url=sme.installateur-alarme-proxeo.fr HTTP/1.1", "request_method": "GET", "http_referrer": "-", 
```

**Comment by tristanbes** [comment]
I've just re-enable the banlist to get logs:
https://gist.github.com/tristanbes/c5314c0b7a5f676942caf4ef37066eff

```
![1__root_lux___etc_nginx_bots_d__ssh_](https://user-images.githubusercontent.com/346010/28277455-54e1494e-6b1a-11e7-98d0-a02357b1bc2b.png)

**Comment by tristanbes** [comment]
You tested on the admin part, where I disabled definitly the banlist for another kind of issue. But the original one for http://julien-moyret-parqueteur.specialisteparquet.com/ (and http://*.specialisteparquet.com/ ) websites is still happening

**Comment by mitchellkrogza** [comment]
Thanks, will have a look through this again in the morning

**Comment by mitchellkrogza** [comment]
Something must be going wrong between Nginx and Varnish / Reverse Proxying setup. Really not 100% sure of your setup but something is clashing.

Virtually any test I run using the latest blacklist allows everything through.

```
curl -I https://mitchellkrog.com -e http://specialisteparquet.com/js/fancybox.min.js
HTTP/1.1 200 OK
```

```
curl -I https://mitchellkrog.com -e http://*.specialisteparquet.com/js/fancybox.min.js
HTTP/1.1 200 OK
```

```
curl -A "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36" https://mitchellkrog.com
<!DOCTYPE html>
<html lang="en-US" prefix="og: http://ogp.me/ns#">
```

```
curl -I https://mitchellkrog.com -e http://anything.specialisteparquet.com/js/fancybox.min.js
HTTP/1.1 200 OK
```

```
curl -I https://mitchellkrog.com -e http://whatever.whatever-whatever.something.nothing.specialisteparquet.com/js/fancybox.min.js
HTTP/1.1 200 OK
```

Hard to figure this one out @tristanbes but something is clashing somewhere.

**Comment by mitchellkrogza** [comment]
@tristanbes is there any way you can test on just Nginx without Varnish or any reverse proxying?

Or try modifying L6451>L6454 from this:

```
geo $ratelimited {
	default 1;
	127.0.0.1 0;
}
```

to this

```
geo $ratelimited {
	default 1;
	127.0.0.1 0;
        185.22.198.8 0;
        10.108.21.210 0;
}
```

And edit include /etc/nginx/bots.d/whitelist-ips.conf so that it looks like this.

```
# Add One Entry Per Line - Can Include Ranges like 127.0.0.1/32
127.0.0.1		0;
185.22.198.8     0;
10.108.21.210    0;
```

**Comment by mitchellkrogza** [comment]
@tristanbes any updates on this?

**Comment by tristanbes** [comment]
Hello,
Sorry for the delay, i was vacationning.

Unfortunatly, I can't test without varnish, but I did try your modifications just now, without any success

**Comment by tristanbes** [comment]
well, maybe, but i'm really not convince since it does nothing except asking the page to nginx (not even caching it).

Is it possible just to use the badbots feature and not the referrer ? That was, in the first place, why I used your code

**Comment by mitchellkrogza** [comment]
Can we move this to: https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/issues

**Comment by mitchellkrogza** [comment]
Also any chance you can post me some of your varnish logs when the blocker is active?

**Comment by tristanbes** [comment]
sure: https://gist.github.com/tristanbes/ce84b55d91ce7c606bc5960bd0b21657

**Comment by mitchellkrogza** [comment]
@tristanbes Please Try this

`sudo wget https://raw.githubusercontent.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/master/conf.d/globalblacklist-botsonly.conf -O /etc/nginx/globalblacklist.conf`

Just a test unit for now but only does Bot blocking, let me know.

**Comment by mitchellkrogza** [comment]
I'm working on some changes to the blocker where you will be able to do this with a switch file, activate some or all functions but not had much time yet to get to it. Soon though.

**Comment by tristanbes** [comment]
wow so weird..

It still not working:

`include ..../blockbots.conf;` (which is the file `globalblacklist-botsonly.conf` rename)

and inside my bots.d directory I have : 
```
-rw-r--r-- 1 root root 953 Jun 26 15:08 blockbots.conf
-rw-r--r-- 1 root root 252 Jul  3 17:59 whitelist-domains.conf
-rw-r--r-- 1 root root  97 Jun 26 15:08 whitelist-ips.con
```

and even with that, the website is still broken :O

**Comment by mitchellkrogza** [comment]
Change your blockbots.conf file, remove everything and add this only

```
if ($bad_words) {
  return 444;
}
```

**Comment by mitchellkrogza** [comment]
Then in your vhost only add the following include:

`include /etc/nginx/bots.d/blockbots.conf;` nothing else

**Comment by mitchellkrogza** [comment]
Hang on you must not include globalblacklist.conf in your vhost ..... that file must be in `/etc/nginx/conf.d/blacklist.conf` and your nginx.conf must have the following line in it `include /etc/nginx/conf.d/*.conf;`

Then in your vhost.conf file the only include you add is

`include /etc/nginx/bots.d/blockbots.conf;`

**Comment by tristanbes** [comment]
Well, I feel stupid, The script was taking the banlist from `conf.d/*.conf` and I was updating the one I created in `bots.d`. So my banlist was very old (prior to your original patch)

I've fixed it and now it's working with normal version :-)
I'm sorry for the trouble, thanks for your time !

**Comment by mitchellkrogza** [comment]
Glad you got it sorted @tristanbes ..... see I never give up.
Enjoy.

**Comment by mitchellkrogza** [comment]
@tristanbes can I remove the test unit I put up for you?

**Comment by tristanbes** [comment]
Yes, i've switched to normal version. Thanks for asking.

**Comment by mitchellkrogza** [comment]
Thanks ... done. Enjoy it.
